name: Run Arxiv Sanity Bot

on:
  schedule:
    # Run every 12 hours at 15 min past the hour
    - cron: "15 */12 * * *"
  workflow_dispatch:

jobs:
  run_arxiv_sanity_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run Arxiv Sanity Bot
      run: |
        arxiv-sanity-bot
