name: Run Arxiv Sanity Bot

on:
  schedule:
    # Run every 12 hours at 15 min past the hour
    - cron: "15 */12 * * *"
  workflow_dispatch:

jobs:
  run_arxiv_sanity_bot:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    
    - name: Check if cache exists
      uses: xSAVIKx/artifact-exists-action@v0
      with:
        name: posted_abstracts.parquet

    - uses: actions/download-artifact@v3
      if: steps.check_coverage_artifact.outputs.exists == 'true'
      with:
        name: posted_abstracts.parquet

    - name: Run Arxiv Sanity Bot
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        arxiv-sanity-bot

    - name: Upload cache
      uses: actions/upload-artifact@v3
      with:
        name: posted_abstracts.parquet
        path: posted_abstracts.parquet